version: "3.8"
services:
  gitlab:
    profiles: ['not-start']
    image: gitlab/gitlab-ee:16.10.1-ee.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.carlosmarind.cl'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.carlosmarind.cl'
    ports:
      - '8081:80'
      - '8443:443'
      - '8022:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: '256m'

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    ports:
      - "8082:8081"
      - "8083:8082"
      - "8084:8083"
    volumes:
      - nexus-data:/nexus-data

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: always
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db_sonar:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    depends_on:
      - db_sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  db_sonar:
    image: postgres:12
    container_name: db_sonar
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins_home:
  nexus-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
